#!/bin/sh

# Copyright (c) 2016 yuk7 <yukx00@gmail.com>
# Released under the MIT license
# http://opensource.org/licenses/mit-license.php

cd $(dirname $0)
if [ $# -eq 1 ]
then
	cd $1
	find . -name ".gitkeep" | xargs rm -rf
	find ./* | cpio -o -H newc | gzip -9 > ../$1.cpio.gz
	find . -type d -empty |xargs -i touch '{}'/.gitkeep
	exit
fi

find -maxdepth 1 -type d -name "*_ramdisk" | xargs -n1 $0
